// examples/react-example.jsx
import React, { useEffect, useRef, useState } from 'react';
import InfiniteTextScroller from 'infinite-text-scroller';

// 1. React 훅 사용 예시
export const useTextScroller = (config) => {
  const scrollerRef = useRef(null);
  const containerId = `scroller-${Math.random().toString(36).substr(2, 9)}`;

  useEffect(() => {
    if (!config.text) return;

    const instance = InfiniteTextScroller.create({ ...config, containerId });
    scrollerRef.current = instance;

    return () => {
      if (scrollerRef.current) {
        scrollerRef.current.destroy();
      }
    };
  }, [config.text]); // 텍스트가 변경되면 다시 생성

  return { containerId, scroller: scrollerRef.current };
};

// 2. React 컴포넌트 래퍼 예시
export const TextScroller = ({ config }) => {
  const { containerId } = useTextScroller(config);
  return <div id={containerId} />;
};

// 사용 예시
const App = () => {
  const [text, setText] = useState('React와 함께 사용하는 무한 스크롤러입니다.');

  const scrollerConfig = {
    text: text,
    speed: 25,
    textColor: 'blue',
  };

  return (
    <div>
      <h1>React 예제</h1>
      <TextScroller config={scrollerConfig} />
      <button onClick={() => setText('텍스트가 업데이트 되었습니다!')}>
        텍스트 변경
      </button>
    </div>
  );
};

export default App;

// examples/vue-example.vue
<template>
  <div>
    <h1>Vue 예제</h1>
    <div :id="containerId"></div>
    <button @click="updateText">텍스트 변경</button>
  </div>
</template>

<script>
import { defineComponent, onMounted, onBeforeUnmount, ref } from 'vue';
import InfiniteTextScroller from 'infinite-text-scroller';

export default defineComponent({
  name: 'VueTextScrollerExample',
  props: {
    config: {
      type: Object,
      required: true,
    },
  },
  setup(props) {
    const scrollerInstance = ref(null);
    const containerId = `vue-scroller-${Date.now()}`;

    onMounted(() => {
      scrollerInstance.value = InfiniteTextScroller.create({
        ...props.config,
        containerId,
      });
    });

    onBeforeUnmount(() => {
      if (scrollerInstance.value) {
        scrollerInstance.value.destroy();
      }
    });

    const updateText = () => {
      if (scrollerInstance.value) {
        scrollerInstance.value.updateText('Vue에서 텍스트가 성공적으로 변경되었습니다!');
      }
    };

    return {
      containerId,
      updateText,
    };
  },
});

/*
// 컴포넌트 사용 예시
<template>
  <VueTextScrollerExample :config="scrollerConfig" />
</template>

<script>
import VueTextScrollerExample from './VueTextScrollerExample.vue';

export default {
  components: { VueTextScrollerExample },
  data() {
    return {
      scrollerConfig: {
        text: 'Vue와 함께 사용하는 무한 스크롤러',
        speed: 30,
        backgroundColor: '#42b883',
        textColor: '#ffffff',
      },
    };
  },
};
</script>
*/
</script>
